
'use strict';
const DATA=window.LEARNING_DATA_V2, LESSONS=DATA.lessons, COURSES=DATA.courses;
const PASS='09090c74379eedfd5cb1abf8fbcf40f0933937fd4e1a9d5f63982f43a18f304f';
const KEY={p:'patternlab.v2.progress',s:'patternlab.v2.settings',a:'patternlab.auth.v1'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=s=>String(s??'').toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9가-힣']+/g,' ').trim();
const today=()=>new Date().toISOString().slice(0,10); const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}} function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
let settings=Object.assign({theme:'system',fontScale:1,dailyGoal:10,ttsRate:.9,course:'all',quizSize:10,hideContext:false},load(KEY.s,{}));
let progress=Object.assign({lessons:{},history:{},quiz:[]},load(KEY.p,{}));
let view='home',courseFilter=settings.course||'all',learnQ='',currentId='b001',tab='examples',cardQueue=[],cardIndex=0,cardFlip=false,quiz=null,libQ='',libSource='all',libPage=1,installPrompt=null;
function st(id){if(!progress.lessons[id])progress.lessons[id]={status:'new',favorite:false,notes:'',reviews:0,interval:0,due:today(),last:null};return progress.lessons[id]}
function commit(){save(KEY.p,progress)}
function toast(m){let t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function applyTheme(){let t=settings.theme;if(t==='system')t=matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light';document.documentElement.dataset.theme=t;document.documentElement.style.setProperty('--fs',settings.fontScale)}
applyTheme();
function migrateV1(){const old=load('p100.progress.v3',null);if(!old?.patterns||localStorage.getItem('patternlab.v2.migrated'))return;Object.entries(old.patterns).forEach(([n,v])=>{const id='p'+String(n).padStart(3,'0');progress.lessons[id]=Object.assign(st(id),v)});save('patternlab.v2.migrated',true);commit();toast('V1 학습 진도를 가져왔습니다')}
async function sha(s){const b=new TextEncoder().encode(s),h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function authOK(){try{if(sessionStorage.getItem(KEY.a)==='ok')return true;const a=JSON.parse(localStorage.getItem(KEY.a)||'null');return a?.expires>Date.now()}catch{return false}}
function unlock(){$('#auth').classList.add('hide');$('#shell').classList.remove('hide');init()}
if(authOK())unlock();
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();$('#authMsg').textContent='확인 중…';if(await sha($('#pw').value)===PASS){if($('#remember').checked)localStorage.setItem(KEY.a,JSON.stringify({expires:Date.now()+7*864e5}));else sessionStorage.setItem(KEY.a,'ok');$('#authMsg').textContent='';unlock()}else{$('#authMsg').textContent='비밀번호가 일치하지 않습니다.';$('#pw').select()}});
$('#pwToggle').onclick=()=>{let x=$('#pw');x.type=x.type==='password'?'text':'password';$('#pwToggle').textContent=x.type==='password'?'보기':'숨김'};
function init(){if(init.done)return;init.done=true;migrateV1();bind();renderSettings();go('home');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function bind(){
 $$('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));
 $('#settingsBtn').onclick=()=>{renderSettings();$('#settings').showModal()};
 $('#randomBtn').onclick=()=>{let a=filteredLessons();currentId=a[Math.floor(Math.random()*a.length)]?.id||'b001';go('learn')};
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').classList.remove('hide')});
 $('#install').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install').classList.add('hide')};
 matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>{if(settings.theme==='system')applyTheme()});
}
function go(v){view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));({home:renderHome,learn:renderLearn,cards:renderCards,quiz:renderQuiz,library:renderLibrary,stats:renderStats}[v]||renderHome)();window.scrollTo({top:0,behavior:'smooth'})}
function filteredLessons(){return LESSONS.filter(l=>courseFilter==='all'||l.course===courseFilter)}
function statusCount(course,status){return LESSONS.filter(l=>(course==='all'||l.course===course)&&st(l.id).status===status).length}
function dueCount(course='all'){return LESSONS.filter(l=>(course==='all'||l.course===course)&&st(l.id).reviews>0&&st(l.id).due<=today()).length}
function courseProgress(id){const a=LESSONS.filter(l=>l.course===id),done=a.filter(l=>st(l.id).status==='mastered').length;return Math.round(done/a.length*100)}
function markActivity(id,type='learned'){const d=today();if(!progress.history[d])progress.history[d]={learned:[],reviews:0,quiz:0};if(type==='learned'&&!progress.history[d].learned.includes(id))progress.history[d].learned.push(id);else if(type==='reviews')progress.history[d].reviews++;else if(type==='quiz')progress.history[d].quiz++;commit()}
function courseName(c){return COURSES.find(x=>x.id===c)?.title||c}
function renderHome(){
 const mastered=statusCount('all','mastered'), learning=statusCount('all','learning'), due=dueCount(), fav=LESSONS.filter(l=>st(l.id).favorite).length;
 $('#home').innerHTML=`<div class="hero"><div class="hero-main"><p class="eyebrow" style="color:#a8c8ff">ENGLISH PATTERN LAB · V2</p><h1>200 patterns.<br>Speak, recall, repeat.</h1><p>세 개의 대본 자료를 한 곳에 묶어 패턴 학습·듣기·말하기·카드 복습·퀴즈·전체 표현 검색으로 구성했습니다.</p><div class="hero-actions"><button class="btn primary" id="continue">이어 학습</button><button class="btn" id="dueHome">복습 ${due}개</button><button class="btn" id="statsHome">진도 보기</button></div></div><div class="hero-side"><div class="metric"><strong>200</strong><span>총 학습 패턴</span></div><div class="metric"><strong>${DATA.stats.expressionCount.toLocaleString()}</strong><span>검색 표현</span></div><div class="metric"><strong>${mastered}</strong><span>완료 패턴</span></div><div class="metric"><strong>${fav}</strong><span>즐겨찾기</span></div></div></div>
 <div class="section-head"><div><h2>학습 코스</h2><p>원자료를 분리해 선택적으로 학습할 수 있습니다.</p></div></div><div class="grid2">${COURSES.map(c=>`<article class="course-card"><span class="course-badge">${c.short}</span><h3>${c.title}</h3><p>${c.description}</p><div class="progress"><i style="width:${courseProgress(c.id)}%"></i></div><div class="tiny muted">완료 ${courseProgress(c.id)}% · ${statusCount(c.id,'learning')}개 학습 중</div><div style="margin-top:14px"><button class="btn primary course-open" data-course="${c.id}">코스 열기</button></div></article>`).join('')}</div>
 <div class="section-head"><div><h2>오늘의 빠른 학습</h2><p>목표 ${settings.dailyGoal}개 · 학습 기록은 이 브라우저에 저장됩니다.</p></div></div><div class="grid2"><div class="course-card"><h3>랜덤 1개</h3><p>두 코스에서 임의의 패턴을 즉시 학습합니다.</p><button class="btn" id="randomHome">랜덤 시작</button></div><div class="course-card"><h3>복습 대기</h3><p>간격 반복 일정이 지난 카드 ${due}개가 있습니다.</p><button class="btn" id="reviewHome">카드 복습</button></div></div>`;
 $('#continue').onclick=()=>go('learn');$('#statsHome').onclick=()=>go('stats');$('#dueHome').onclick=$('#reviewHome').onclick=()=>go('cards');$('#randomHome').onclick=()=>$('#randomBtn').click();
 $$('.course-open').forEach(b=>b.onclick=()=>{courseFilter=b.dataset.course;settings.course=courseFilter;save(KEY.s,settings);currentId=LESSONS.find(l=>l.course===courseFilter)?.id;go('learn')});
}
function renderLearn(){
 let all=filteredLessons().filter(l=>!learnQ||norm(l.title+' '+l.meaning).includes(norm(learnQ)));
 let cur=LESSONS.find(l=>l.id===currentId);if(!cur||!all.some(x=>x.id===cur.id)){cur=all[0]||filteredLessons()[0];if(cur)currentId=cur.id}
 $('#learn').innerHTML=`<div class="toolbar"><div class="search">⌕ <input id="learnQ" placeholder="패턴·뜻 검색" value="${esc(learnQ)}"></div><select id="courseSel"><option value="all">전체 200</option>${COURSES.map(c=>`<option value="${c.id}" ${courseFilter===c.id?'selected':''}>${c.title}</option>`).join('')}</select><select id="statusSel"><option value="all">전체 상태</option><option value="favorite">즐겨찾기</option><option value="new">미학습</option><option value="learning">학습 중</option><option value="mastered">완료</option></select></div><div class="learn-layout"><div class="lesson-list" id="lessonList"></div><div class="panel lesson-detail" id="detail"></div></div>`;
 $('#learnQ').oninput=e=>{learnQ=e.target.value;renderLessonList()};$('#courseSel').onchange=e=>{courseFilter=e.target.value;settings.course=courseFilter;save(KEY.s,settings);renderLearn()};$('#statusSel').onchange=renderLessonList;renderLessonList();renderDetail();
}
function renderLessonList(){
 const box=$('#lessonList');if(!box)return;let filter=$('#statusSel')?.value||'all';let a=filteredLessons().filter(l=>!learnQ||norm(l.title+' '+l.meaning).includes(norm(learnQ))).filter(l=>filter==='all'||filter==='favorite'?filter==='all'||st(l.id).favorite:st(l.id).status===filter);
 box.innerHTML=a.length?a.map(l=>`<button class="lesson-item ${l.id===currentId?'active':''}" data-id="${l.id}"><span class="lesson-no">${l.course==='pattern'?'P':'B'}${String(l.lesson).padStart(2,'0')}</span><span><b>${esc(l.title)}</b><small>${esc(l.meaning)}</small></span><i class="status-dot ${st(l.id).status}"></i></button>`).join(''):`<div class="empty">조건에 맞는 패턴이 없습니다.</div>`;
 $$('.lesson-item').forEach(b=>b.onclick=()=>{currentId=b.dataset.id;renderLessonList();renderDetail();if(innerWidth<900)$('#detail').scrollIntoView({behavior:'smooth',block:'start'})});
}
function renderDetail(){
 const l=LESSONS.find(x=>x.id===currentId),box=$('#detail');if(!l||!box)return;const ps=st(l.id);markActivity(l.id,'learned');
 box.innerHTML=`<div class="detail-top"><div><span class="course-badge">${courseName(l.course)} · ${l.lesson}/100</span><h1 class="pattern">${esc(l.title)}</h1><p class="meaning">${esc(l.meaning)}</p><div class="tags">${(l.tags||[]).map(t=>`<span class="pill">${esc(t)}</span>`).join('')}<span class="pill">대본 ${l.sourceStart||''}${l.sourceEnd?'–'+l.sourceEnd:''}줄</span></div></div><button class="icon" id="favBtn" title="즐겨찾기">${ps.favorite?'★':'☆'}</button></div>
 <div class="actionbar"><button class="btn primary" data-speak="${esc(l.title)}">🔊 패턴 듣기</button><button class="btn" data-speech="${esc(l.title)}">🎙 말하기</button><button class="btn" id="shadowBtn">▶ 예문 연속듣기</button><button class="btn ${ps.status==='learning'?'good':''}" id="learningBtn">학습 중</button><button class="btn ${ps.status==='mastered'?'good':''}" id="masterBtn">완료</button></div>
 <div class="tabs">${[['examples','예문'],['vocab','어휘'],['dialogue','미니대화'],['notes','내 문장·메모']].map(([k,n])=>`<button data-tab="${k}" class="${tab===k?'active':''}">${n}</button>`).join('')}</div><div id="tabbody" class="tabbody"></div>`;
 $('#favBtn').onclick=()=>{ps.favorite=!ps.favorite;commit();renderDetail()};$('#learningBtn').onclick=()=>{ps.status='learning';commit();renderDetail();renderLessonList()};$('#masterBtn').onclick=()=>{ps.status='mastered';commit();renderDetail();renderLessonList()};
 $$('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderDetail()});$('#shadowBtn').onclick=()=>shadowLesson(l);bindSpeak();renderTab(l);
}
function renderTab(l){
 const box=$('#tabbody');if(tab==='examples'){box.innerHTML=l.examples?.length?`<div class="example-list">${l.examples.map((e,i)=>`<div class="example"><div><b>${esc(e.en)}</b>${settings.hideContext?'':`<p>${esc(e.context||l.meaning)}</p>`}<div class="source">대본 문맥 · line ${e.line||'-'}</div></div><div class="ex-actions"><button class="icon" data-speak="${esc(e.en)}">🔊</button><button class="icon" data-speech="${esc(e.en)}">🎙</button></div></div>`).join('')}</div>`:`<div class="empty">예문 인덱스가 없습니다.</div>`}
 if(tab==='vocab'){box.innerHTML=l.vocab?.length?`<div class="vocab-grid">${l.vocab.map(v=>`<div class="vocab"><b>${esc(v.en)}</b><span>${esc(v.context||'대본 어휘')}</span><div class="source">line ${v.line||'-'}</div></div>`).join('')}</div>`:`<div class="empty">이 코스의 원자료에서는 별도 어휘 목록을 자동 구성하지 않았습니다.</div>`}
 if(tab==='dialogue'){box.innerHTML=l.dialogue?.length?`<div class="dialogue">${l.dialogue.map(d=>`<div class="bubble"><b>${esc(d.en)}</b><div class="source">line ${d.line||'-'}</div></div>`).join('')}</div><div style="margin-top:10px"><button class="btn" id="dialogPlay">대화 연속듣기</button></div>`:`<div class="empty">이 강의에서 독립적인 대화 묶음을 찾지 못했습니다.</div>`;$('#dialogPlay')?.addEventListener('click',()=>speakSequence(l.dialogue.map(x=>x.en)))}
 if(tab==='notes'){box.innerHTML=`<p class="muted tiny">패턴을 이용해 자신의 문장 3개를 적어 보세요.</p><textarea class="notes" id="note">${esc(st(l.id).notes||'')}</textarea><div style="margin-top:8px"><button class="btn primary" id="saveNote">저장</button></div>`;$('#saveNote').onclick=()=>{st(l.id).notes=$('#note').value;commit();toast('메모를 저장했습니다')}}
 bindSpeak();
}
function bindSpeak(){$$('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak));$$('[data-speech]').forEach(b=>b.onclick=()=>openSpeech(b.dataset.speech))}
function speak(text,rate=settings.ttsRate){if(!('speechSynthesis'in window)){toast('이 브라우저는 TTS를 지원하지 않습니다');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=rate;speechSynthesis.speak(u)}
function speakSequence(arr){if(!arr?.length)return;let i=0;speechSynthesis.cancel();function next(){if(i>=arr.length)return;const u=new SpeechSynthesisUtterance(arr[i++]);u.lang='en-US';u.rate=settings.ttsRate;u.onend=()=>setTimeout(next,300);speechSynthesis.speak(u)}next()}
function shadowLesson(l){speakSequence((l.examples||[]).slice(0,8).map(x=>x.en))}
function similarity(a,b){a=norm(a).split(' ');b=norm(b).split(' ');if(!a.length||!b.length)return 0;const A=new Set(a),B=new Set(b),inter=[...A].filter(x=>B.has(x)).length;return Math.round(200*inter/(A.size+B.size))}
function openSpeech(text){const d=$('#speech'),box=$('#speechBody');box.innerHTML=`<div class="speech-target">${esc(text)}</div><button class="btn primary" id="rec">🎙 말하기 시작</button><div id="speechResult" class="muted tiny">Chrome 계열 브라우저에서 음성 인식을 사용할 수 있습니다.</div>`;d.showModal();$('#rec').onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast('이 브라우저는 음성 인식을 지원하지 않습니다');return}const r=new R();r.lang='en-US';r.interimResults=false;$('#speechResult').textContent='듣는 중…';r.onresult=e=>{const said=e.results[0][0].transcript,score=similarity(text,said);$('#speechResult').innerHTML=`<div class="score" style="--p:${score}%"><b>${score}</b></div><p><b>인식:</b> ${esc(said)}</p><p><b>목표:</b> ${esc(text)}</p>`};r.onerror=()=>$('#speechResult').textContent='인식하지 못했습니다. 다시 시도해 주세요.';r.start()}}
function makeCardQueue(){let a=filteredLessons(),due=a.filter(l=>st(l.id).reviews>0&&st(l.id).due<=today());cardQueue=due.length?shuffle(due):shuffle(a.filter(l=>st(l.id).status!=='mastered')).slice(0,30);if(!cardQueue.length)cardQueue=shuffle(a).slice(0,30);cardIndex=0;cardFlip=false}
function renderCards(){if(!cardQueue.length)makeCardQueue();const l=cardQueue[cardIndex%cardQueue.length];if(!l){$('#cards').innerHTML='<div class="empty">카드가 없습니다.</div>';return}$('#cards').innerHTML=`<div class="section-head"><div><h2>간격 반복 카드</h2><p>${courseFilter==='all'?'전체 코스':courseName(courseFilter)} · ${cardIndex+1}/${cardQueue.length}</p></div><button class="btn" id="newQueue">새 큐</button></div><div class="flash-wrap"><div class="flash ${cardFlip?'flipped':''}" id="flash"><div class="flash-inner"><div class="face"><span class="course-badge">${l.course==='pattern'?'P':'B'}${String(l.lesson).padStart(3,'0')}</span><h2>${esc(l.title)}</h2><p class="muted">카드를 눌러 뜻 보기</p></div><div class="face back"><h2 style="font-size:2rem">${esc(l.meaning)}</h2><p class="muted">${esc(l.examples?.[0]?.en||l.title)}</p></div></div></div><div class="rating">${[['again','Again'],['hard','Hard'],['good','Good'],['easy','Easy']].map(([k,n])=>`<button data-rate="${k}"><b>${n}</b></button>`).join('')}</div></div>`;$('#flash').onclick=()=>{cardFlip=!cardFlip;renderCards()};$('#newQueue').onclick=()=>{makeCardQueue();renderCards()};$$('[data-rate]').forEach(b=>b.onclick=e=>{e.stopPropagation();rateCard(l,b.dataset.rate)})}
function rateCard(l,r){const p=st(l.id),map={again:[0,0],hard:[1,1],good:[2,3],easy:[3,7]},[inc,days]=map[r];p.reviews++;p.interval=Math.max(days,p.interval+inc);let d=new Date();d.setDate(d.getDate()+p.interval);p.due=d.toISOString().slice(0,10);p.last=today();if(r==='again')p.status='learning';if(r==='good'&&p.reviews>=3)p.status='mastered';if(r==='easy')p.status='mastered';markActivity(l.id,'reviews');cardIndex++;cardFlip=false;if(cardIndex>=cardQueue.length){makeCardQueue();toast('복습 큐를 완료했습니다')}renderCards()}
function quizPool(){return filteredLessons()}
function renderQuiz(){if(!quiz){$('#quiz').innerHTML=`<div class="quiz-shell"><div class="section-head"><div><h2>퀴즈</h2><p>패턴 뜻·역방향·듣기·직접 입력</p></div></div><div class="grid2">${[['enko','영어 → 한국어'],['koen','한국어 → 영어'],['listen','듣고 뜻 고르기'],['type','한국어 → 영어 입력']].map(([k,n])=>`<button class="course-card" data-qmode="${k}" style="text-align:left"><h3>${n}</h3><p>${settings.quizSize}문제 · ${courseFilter==='all'?'전체 코스':courseName(courseFilter)}</p></button>`).join('')}</div></div>`;$$('[data-qmode]').forEach(b=>b.onclick=()=>startQuiz(b.dataset.qmode));return}renderQuizQuestion()}
function startQuiz(mode){let pool=shuffle(quizPool()).slice(0,Math.min(settings.quizSize,quizPool().length));quiz={mode,pool,i:0,score:0,answered:false};renderQuizQuestion()}
function renderQuizQuestion(){if(quiz.i>=quiz.pool.length){const pct=Math.round(quiz.score/quiz.pool.length*100);progress.quiz.push({date:today(),score:pct,n:quiz.pool.length});markActivity('', 'quiz');$('#quiz').innerHTML=`<div class="quiz-shell"><div class="panel quiz-card" style="text-align:center"><p class="eyebrow">RESULT</p><h1 style="font-size:4rem;margin:8px">${pct}%</h1><p>${quiz.score}/${quiz.pool.length} 정답</p><button class="btn primary" id="againQuiz">다시 풀기</button><button class="btn" id="endQuiz">끝내기</button></div></div>`;$('#againQuiz').onclick=()=>{let m=quiz.mode;quiz=null;startQuiz(m)};$('#endQuiz').onclick=()=>{quiz=null;renderQuiz()};return}
 const l=quiz.pool[quiz.i], mode=quiz.mode, q=(mode==='enko'||mode==='listen')?l.title:l.meaning;let choices=shuffle([l,...shuffle(quizPool().filter(x=>x.id!==l.id)).slice(0,3)]);$('#quiz').innerHTML=`<div class="quiz-shell"><div class="panel quiz-card"><div class="tiny muted">${quiz.i+1}/${quiz.pool.length} · ${quiz.score} correct</div>${mode==='listen'?`<button class="btn primary" id="listenQ">🔊 듣기</button><div class="quiz-q">문장을 듣고 뜻을 고르세요.</div>`:`<div class="quiz-q">${esc(q)}</div>`}${mode==='type'?`<div class="typing"><input id="typeAns" autocomplete="off" placeholder="영어로 입력"><button class="btn primary" id="typeSubmit">확인</button></div>`:`<div class="choices">${choices.map(x=>`<button class="choice" data-answer="${x.id}">${esc((mode==='enko'||mode==='listen')?x.meaning:x.title)}</button>`).join('')}</div>`}<div id="qfb"></div></div></div>`;if(mode==='listen'){$('#listenQ').onclick=()=>speak(l.title);setTimeout(()=>speak(l.title),200)}if(mode==='type'){$('#typeSubmit').onclick=()=>answerType(l);$('#typeAns').onkeydown=e=>{if(e.key==='Enter')answerType(l)}}else $$('.choice').forEach(b=>b.onclick=()=>answerChoice(l,b));}
function nextQuiz(){setTimeout(()=>{quiz.i++;quiz.answered=false;renderQuizQuestion()},700)}
function answerChoice(l,b){if(quiz.answered)return;quiz.answered=true;const ok=b.dataset.answer===l.id;if(ok){quiz.score++;b.classList.add('correct')}else{b.classList.add('wrong');document.querySelector(`[data-answer="${l.id}"]`)?.classList.add('correct')}nextQuiz()}
function answerType(l){if(quiz.answered)return;quiz.answered=true;const a=$('#typeAns').value,score=similarity(l.title,a),ok=score>=88;if(ok)quiz.score++;$('#qfb').innerHTML=`<div class="example" style="margin-top:12px"><div><b>${ok?'정답':'확인해 보세요'} · ${score}%</b><p>${esc(l.title)}</p></div></div>`;nextQuiz()}
function renderLibrary(){let q=norm(libQ),a=DATA.library.filter(x=>(libSource==='all'||x.source===libSource)&&(!q||norm(x.en+' '+x.ko).includes(q))),pageSize=50,pages=Math.max(1,Math.ceil(a.length/pageSize));libPage=Math.min(libPage,pages);let rows=a.slice((libPage-1)*pageSize,libPage*pageSize);const sources=[...new Set(DATA.library.map(x=>x.source))];$('#library').innerHTML=`<div class="toolbar"><div class="search">⌕ <input id="libQ" placeholder="영어·한글 표현 검색" value="${esc(libQ)}"></div><select id="libSource"><option value="all">전체 자료</option>${sources.map(s=>`<option ${libSource===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div><div class="section-head"><div><h2>전체 표현 사전</h2><p>${a.length.toLocaleString()}개 검색 결과 · 반복 제거 인덱스</p></div></div><div class="library-list">${rows.map(x=>`<div class="expr-card"><div><b>${esc(x.en)}</b><p>${esc(x.ko||'대본 내 독립 표현')}</p><span class="source">${esc(x.source)} · line ${x.line||'-'}</span></div><button class="icon" data-speak="${esc(x.en)}">🔊</button></div>`).join('')}</div><div class="pager"><button class="btn" id="prevPage">이전</button><span class="tiny muted">${libPage}/${pages}</span><button class="btn" id="nextPage">다음</button></div>`;$('#libQ').oninput=e=>{libQ=e.target.value;libPage=1;renderLibrary()};$('#libSource').onchange=e=>{libSource=e.target.value;libPage=1;renderLibrary()};$('#prevPage').onclick=()=>{libPage=Math.max(1,libPage-1);renderLibrary()};$('#nextPage').onclick=()=>{libPage=Math.min(pages,libPage+1);renderLibrary()};bindSpeak()}
function renderStats(){const m=statusCount('all','mastered'),l=statusCount('all','learning'),n=200-m-l,f=LESSONS.filter(x=>st(x.id).favorite).length;$('#stats').innerHTML=`<div class="section-head"><div><h2>학습 통계</h2><p>현재 브라우저의 로컬 진도입니다.</p></div></div><div class="stats-grid"><div class="panel stat"><strong>${m}</strong><span>완료</span></div><div class="panel stat"><strong>${l}</strong><span>학습 중</span></div><div class="panel stat"><strong>${dueCount()}</strong><span>복습 예정</span></div><div class="panel stat"><strong>${f}</strong><span>즐겨찾기</span></div></div><div class="section-head"><div><h2>코스별 완료율</h2></div></div><div class="panel" style="padding:18px">${COURSES.map(c=>`<div class="barrow"><span>${c.title}</span><div class="progress"><i style="width:${courseProgress(c.id)}%"></i></div><b>${courseProgress(c.id)}%</b></div>`).join('')}</div><div class="section-head"><div><h2>데이터 구성</h2></div></div><div class="panel" style="padding:18px"><div class="barrow"><span>총 패턴</span><div></div><b>200</b></div><div class="barrow"><span>검색 표현</span><div></div><b>${DATA.stats.expressionCount}</b></div><div class="barrow"><span>기존 대본</span><div></div><b>100</b></div><div class="barrow"><span>추가 대본</span><div></div><b>100</b></div></div>`}
function renderSettings(){const b=$('#settingsBody');b.innerHTML=`<div class="setting"><div><label>테마</label><small>화면 색상</small></div><select id="theme"><option value="system">시스템</option><option value="light">라이트</option><option value="dark">다크</option></select></div><div class="setting"><div><label>글자 크기</label><small>모바일 가독성</small></div><input id="font" type="range" min=".9" max="1.25" step=".05" value="${settings.fontScale}"></div><div class="setting"><div><label>TTS 속도</label><small>영어 듣기</small></div><input id="rate" type="range" min=".6" max="1.2" step=".05" value="${settings.ttsRate}"></div><div class="setting"><div><label>퀴즈 문항</label></div><input id="qsize" type="number" min="5" max="50" value="${settings.quizSize}"></div><div class="setting"><div><label>대본 문맥 숨기기</label><small>영어만 집중해서 보기</small></div><input id="hideContext" type="checkbox" ${settings.hideContext?'checked':''}></div><div><button class="btn" id="exportBtn">진도 내보내기</button> <button class="btn" id="importBtn">진도 가져오기</button> <button class="btn bad" id="lockBtn">잠금</button></div><p class="tiny muted">V2는 기존 V1의 <code>p100.progress.v3</code> 진도를 처음 실행할 때 자동으로 기존 100패턴에 연결합니다.</p>`;
 $('#theme').value=settings.theme;$('#theme').onchange=e=>{settings.theme=e.target.value;save(KEY.s,settings);applyTheme()};$('#font').oninput=e=>{settings.fontScale=+e.target.value;save(KEY.s,settings);applyTheme()};$('#rate').oninput=e=>{settings.ttsRate=+e.target.value;save(KEY.s,settings)};$('#qsize').onchange=e=>{settings.quizSize=Math.max(5,Math.min(50,+e.target.value||10));save(KEY.s,settings)};$('#hideContext').onchange=e=>{settings.hideContext=e.target.checked;save(KEY.s,settings)};$('#exportBtn').onclick=exportProgress;$('#importBtn').onclick=()=>$('#importFile').click();$('#lockBtn').onclick=()=>{localStorage.removeItem(KEY.a);sessionStorage.removeItem(KEY.a);location.reload()};$('#importFile').onchange=importProgress}
function exportProgress(){const blob=new Blob([JSON.stringify({version:2,settings,progress},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english-pattern-lab-v2-progress.json';a.click();URL.revokeObjectURL(a.href)}
function importProgress(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.progress)progress=x.progress;if(x.settings)settings=Object.assign(settings,x.settings);commit();save(KEY.s,settings);applyTheme();toast('진도를 가져왔습니다');renderSettings()}catch{toast('올바른 진도 파일이 아닙니다')}};r.readAsText(f)}
